### ISSUE TITLE
Add a rule to warn on TODO comments

### ISSUE THREAD

**Issue by tdmalone** [ChromatixAU/phpcs-config-chromatix#14]
`Generic.Commenting.Todo.CommentFound` seems to do this, but on previous testing it did not seem to work. It may well work now if we try again!

**Comment by amritcheema25** [comment]
Hey @tdmalone , Yes its working now. I tested on ipx. Just un-comment the code. 
`<rule ref="Generic.Commenting.Todo.CommentFound">
    <severity>5</severity>
  </rule>`

**Comment by tdmalone** [comment]
Oh, excellent! @amritcheema25 Can you make that change to this config? You can commit it directly to master. Then, add a version tag, and that will automatically [deploy to Packagist](https://packagist.org/packages/chromatix/phpcs-config-chromatix), which means Composer will then bring the latest version down for new projects.

**Comment by amritcheema25** [comment]
Done . https://github.com/ChromatixAU/phpcs-config-chromatix/commit/d2f6b78da2d76062fe30f4b36c8e851578b47ca0

**Comment by tdmalone** [comment]
Thanks @amritcheema25! Don't forget the tag too :) (if you created it locally you'll need to `git push --tags`)

**Comment by tdmalone** [comment]
You can see the latest tags [here](https://github.com/ChromatixAU/phpcs-config-chromatix/releases)
