### ISSUE TITLE
get_previous_post() and get_next_post() are not allowed

### ISSUE THREAD

**Issue by ffxffxwu** [ChromatixAU/phpcs-config-chromatix#18]
| ERROR | [ ] get_next_post() is highly discouraged due to not being
         |       |     cached; please use wpcom_vip_get_adjacent_post()
         |       |     instead.
         |       |     (WordPress.VIP.RestrictedFunctions.get_adjacent_post_get_next_post)

| ERROR | [ ] get_previous_post() is highly discouraged due to not
         |       |     being cached; please use wpcom_vip_get_adjacent_post()
         |       |     instead.
         |       |     (WordPress.VIP.RestrictedFunctions.get_adjacent_post_get_previous_post)

**Comment by tdmalone** [comment]
Fixed in [v0.0.14](https://github.com/ChromatixAU/phpcs-config-chromatix/releases/tag/v0.0.14) of phpcs-config-chromatix.

@ffxffxwu You can run `composer update chromatix/phpcs-config-chromatix` to update your version.
