### ISSUE TITLE
Empty line should be allowed before block comment

### ISSUE THREAD

**Issue by tdmalone** [ChromatixAU/phpcs-config-chromatix#9]
`Squiz.Commenting.BlockComment.HasEmptyLineBefore`

It's a bit of a useless rule, as an empty line before a comment might actually be useful for separation.

**Comment by amritcheema25** [comment]
Exclude `Squiz.Commenting.BlockComment.NoEmptyLineBefore` to fix it.

**Comment by amritcheema25** [comment]
Updated in github. Refer to commit : https://github.com/ChromatixAU/phpcs-config-chromatix/commit/d2f6b78da2d76062fe30f4b36c8e851578b47ca0
